version: '3'
services:
  app1:
    image: 4hard/app1:1.0
    networks:
      - intuitive
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  
    
    
    
  app2:
    image: 4hard/app2:1.0
    networks:
      - intuitive
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  proxy:
    image: nginx
    networks:
      - intuitive
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt  
networks:
  intuitive:
    external: true
